# Quando for rodar em homologacao
# docker compose --env-file .env.hml build
# docker compose --env-file .env.hml up -d

# Quando for rodar em producao
# docker compose --env-file .env.prod build
# docker compose --env-file .env.prod up -d

# Quando for rodar local
# docker compose build
# docker compose up -d

services:
  db:
    container_name: sedec_db
    image: postgres:16.0-alpine
    restart: unless-stopped
    env_file:
      - .env.prod
    volumes:
      - sedec-data:/var/lib/postgresql/data/
    ports:
      - "5505:5432"
    networks:
      - intranet

  backend:
    container_name: sedec_strapi
    build:
      context: ./backend-strapi
      dockerfile: Dockerfile.prod
      args:
        PUBLIC_URL: ${PUBLIC_URL:-http://localhost/backend}
    restart: unless-stopped
    env_file:
      - .env.prod
    environment:
      DATABASE_HOST: db
    volumes:
      - ./backend-strapi/config:/opt/app/config
      - ./backend-strapi/src:/opt/app/src
      - ./backend-strapi/package.json:/opt/package.json
      - ./backend-strapi/yarn.lock:/opt/yarn.lock
      - strapi-uploads:/opt/app/public/uploads
    ports:
      - "1337:1337"
    networks:
      - intranet
    depends_on:
      - db

  frontend:
    container_name: sedec_nextjs
    build:
      context: ./frontend-nextjs
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_STRAPI_URL: ${NEXT_PUBLIC_STRAPI_URL:-http://localhost/backend}
    restart: unless-stopped
    env_file:
      - .env.prod
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    networks:
      - intranet
    depends_on:
      - backend

  proxy:
    container_name: sedec_nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - intranet
    depends_on:
      - frontend
      - backend

networks:
  intranet:
    driver: bridge

volumes:
  sedec-data:
  strapi-uploads:
