events {
    worker_connections 1024;
}

http {
    server {
        listen 80;

        # Roteamento Proxy Reverso: /backend/* -> Strapi
        location /backend/ {
            rewrite ^/backend/?(.*)$ /$1 break;
            proxy_pass http://backend:1337;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }

        # Roteamento Proxy Reverso: /* -> Next.js Standalone
        location / {
            proxy_pass http://frontend:3000;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }
    }
}
